/* Formatted on 8/12/2025 6:10:44 PM (QP5 v5.417) */
CREATE OR REPLACE PACKAGE IKIS_RBM.IKIS_RBM_SUBSYSTEM2USER
IS
    -- Author  : JSHPAK
    -- Public function and procedure declarations

    PROCEDURE Delete_SubSystem2User (pwu_id NUMBER);

    PROCEDURE Insert_SubSystem2User (pwu_id NUMBER, pes_id NUMBER);
END IKIS_RBM_SUBSYSTEM2USER;
/


GRANT EXECUTE ON IKIS_RBM.IKIS_RBM_SUBSYSTEM2USER TO DNET_PROXY
/

GRANT EXECUTE ON IKIS_RBM.IKIS_RBM_SUBSYSTEM2USER TO II01RC_RBMWEB_COMMON
/

GRANT EXECUTE ON IKIS_RBM.IKIS_RBM_SUBSYSTEM2USER TO PORTAL_PROXY
/
