/* Formatted on 8/12/2025 6:11:40 PM (QP5 v5.417) */
CREATE OR REPLACE PACKAGE IKIS_SYSWEB.IKIS_HTMLDB_IMG
IS
    -- Author  : YURA_A
    -- Created : 03.03.2006 11:34:01
    -- Purpose : Work with images for web-client

    PROCEDURE show_image (p_img IN OUT NOCOPY BLOB);
END IKIS_HTMLDB_IMG;
/


CREATE OR REPLACE PUBLIC SYNONYM IKIS_HTMLDB_IMG FOR IKIS_SYSWEB.IKIS_HTMLDB_IMG
/


GRANT EXECUTE ON IKIS_SYSWEB.IKIS_HTMLDB_IMG TO IKIS_FINZVIT WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IKIS_HTMLDB_IMG TO IKIS_PERSON WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IKIS_HTMLDB_IMG TO IKIS_RBM WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IKIS_HTMLDB_IMG TO IKIS_WEBPROXY WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IKIS_HTMLDB_IMG TO USS_CEA WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IKIS_HTMLDB_IMG TO USS_DOC WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IKIS_HTMLDB_IMG TO USS_ESR WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IKIS_HTMLDB_IMG TO USS_EXCH WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IKIS_HTMLDB_IMG TO USS_NDI WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IKIS_HTMLDB_IMG TO USS_PERSON WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IKIS_HTMLDB_IMG TO USS_RNSP WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IKIS_HTMLDB_IMG TO USS_RPT WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IKIS_HTMLDB_IMG TO USS_VISIT WITH GRANT OPTION
/


/* Formatted on 8/12/2025 6:11:43 PM (QP5 v5.417) */
CREATE OR REPLACE PACKAGE BODY IKIS_SYSWEB.IKIS_HTMLDB_IMG
IS
    PROCEDURE show_image (p_img IN OUT NOCOPY BLOB)
    AS
    BEGIN
        OWA_UTIL.mime_header ('application/octet', FALSE);
        OWA_UTIL.http_header_close;
        WPG_DOCLOAD.download_file (p_img);
    END show_image;
END IKIS_HTMLDB_IMG;
/