/* Formatted on 8/12/2025 6:11:37 PM (QP5 v5.417) */
CREATE OR REPLACE PROCEDURE IKIS_SYSWEB.SET_CONTEXT_IKIS_SUPPORT
IS
BEGIN
    ikis_sysweb.ikis_web_context.setcontext ('IKIS_SUPPORT');
END SET_CONTEXT_IKIS_SUPPORT;
/
