/* Formatted on 8/12/2025 6:10:09 PM (QP5 v5.417) */
CREATE OR REPLACE PROCEDURE IKIS_SYS.un_disable_triggers
AS
BEGIN
    DSERIALS.gd_ts_enabled := FALSE;
    DSERIALS.gd_tp_enabled := FALSE;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM UN_DISABLE_TRIGGERS FOR IKIS_SYS.UN_DISABLE_TRIGGERS
/


GRANT EXECUTE ON IKIS_SYS.UN_DISABLE_TRIGGERS TO II01RC_IKIS_REPL
/
