/* Formatted on 8/12/2025 6:11:37 PM (QP5 v5.417) */
CREATE OR REPLACE PROCEDURE IKIS_SYSWEB.ViewZip$UNZIPALL (
    p_zip      IN VARCHAR2,
    p_outdir   IN VARCHAR2)
AS
    LANGUAGE JAVA
    NAME 'ViewZip.UNZIPALL (java.lang.String,java.lang.String)' ;
--!!!
/


CREATE OR REPLACE PUBLIC SYNONYM VIEWZIP$UNZIPALL FOR IKIS_SYSWEB.VIEWZIP$UNZIPALL
/


GRANT EXECUTE ON IKIS_SYSWEB.VIEWZIP$UNZIPALL TO IKIS_FINZVIT WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.VIEWZIP$UNZIPALL TO IKIS_PERSON WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.VIEWZIP$UNZIPALL TO IKIS_RBM WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.VIEWZIP$UNZIPALL TO IKIS_WEBPROXY WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.VIEWZIP$UNZIPALL TO USS_CEA WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.VIEWZIP$UNZIPALL TO USS_DOC WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.VIEWZIP$UNZIPALL TO USS_ESR WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.VIEWZIP$UNZIPALL TO USS_EXCH WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.VIEWZIP$UNZIPALL TO USS_NDI WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.VIEWZIP$UNZIPALL TO USS_PERSON WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.VIEWZIP$UNZIPALL TO USS_RNSP WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.VIEWZIP$UNZIPALL TO USS_RPT WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.VIEWZIP$UNZIPALL TO USS_VISIT WITH GRANT OPTION
/
