/* Formatted on 8/12/2025 6:11:37 PM (QP5 v5.417) */
CREATE OR REPLACE PROCEDURE IKIS_SYSWEB.GetUser (
    p_login       w_users.wu_login%TYPE,
    p_pib     OUT w_users.wu_pib%TYPE,
    p_numid   OUT w_users.wu_numid%TYPE)
IS
BEGIN
    ikis_htmldb_auth.GetUser (v ('USER'), p_pib, p_numid);
END GetUser;
/


CREATE OR REPLACE PUBLIC SYNONYM GETUSER FOR IKIS_SYSWEB.GETUSER
/


GRANT EXECUTE ON IKIS_SYSWEB.GETUSER TO II01RC_SYSWEB_COMM
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSER TO IKIS_FINZVIT WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSER TO IKIS_PERSON WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSER TO IKIS_RBM WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSER TO IKIS_WEBPROXY WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSER TO USS_CEA WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSER TO USS_DOC WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSER TO USS_ESR WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSER TO USS_EXCH WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSER TO USS_NDI WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSER TO USS_PERSON WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSER TO USS_RNSP WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSER TO USS_RPT WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSER TO USS_VISIT WITH GRANT OPTION
/
