/* Formatted on 8/12/2025 6:10:09 PM (QP5 v5.417) */
CREATE OR REPLACE PROCEDURE IKIS_SYS.dbms_output_put_lines (p_line VARCHAR2)
IS
    c_line_len   INTEGER := 248;
    l_rest       VARCHAR2 (4000);
    l_out        VARCHAR2 (250);
    i            INTEGER;
BEGIN
    l_rest := RTRIM (p_line);

    IF LENGTH (l_rest) > c_line_len
    THEN
        WHILE LENGTH (l_rest) > 0
        LOOP
            l_out := SUBSTR (l_rest, 1, c_line_len);
            i := LENGTH (l_out);

            WHILE SUBSTR (l_out, i, 1) <> ' '
            LOOP
                i := i - 1;
            END LOOP;

            l_out := RTRIM (SUBSTR (l_rest, 1, i));
            l_rest := RTRIM (SUBSTR (l_rest, i, LENGTH (l_rest)));
            DBMS_OUTPUT.put_line (l_out);

            IF LENGTH (l_rest) < c_line_len
            THEN
                DBMS_OUTPUT.put_line (l_rest);
                l_rest := '';
            END IF;
        END LOOP;
    ELSE
        DBMS_OUTPUT.put_line (l_rest);
    END IF;
END dbms_output_put_lines;
/


CREATE OR REPLACE PUBLIC SYNONYM DBMS_OUTPUT_PUT_LINES FOR IKIS_SYS.DBMS_OUTPUT_PUT_LINES
/


GRANT EXECUTE ON IKIS_SYS.DBMS_OUTPUT_PUT_LINES TO IKIS_FINZVIT WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.DBMS_OUTPUT_PUT_LINES TO IKIS_PERSON WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.DBMS_OUTPUT_PUT_LINES TO IKIS_RBM WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.DBMS_OUTPUT_PUT_LINES TO IKIS_SYSWEB WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.DBMS_OUTPUT_PUT_LINES TO PUBLIC
/

GRANT EXECUTE ON IKIS_SYS.DBMS_OUTPUT_PUT_LINES TO USS_CEA WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.DBMS_OUTPUT_PUT_LINES TO USS_DOC WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.DBMS_OUTPUT_PUT_LINES TO USS_ESR WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.DBMS_OUTPUT_PUT_LINES TO USS_EXCH WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.DBMS_OUTPUT_PUT_LINES TO USS_NDI WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.DBMS_OUTPUT_PUT_LINES TO USS_PERSON WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.DBMS_OUTPUT_PUT_LINES TO USS_RNSP WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.DBMS_OUTPUT_PUT_LINES TO USS_RPT WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.DBMS_OUTPUT_PUT_LINES TO USS_VISIT WITH GRANT OPTION
/
