/* Formatted on 8/12/2025 6:11:37 PM (QP5 v5.417) */
CREATE OR REPLACE PROCEDURE IKIS_SYSWEB.GetUserAttr (
    p_username       w_users.wu_login%TYPE,
    p_uid        OUT w_users.wu_id%TYPE,
    p_wut        OUT w_users.wu_wut%TYPE,
    p_org        OUT w_users.wu_org%TYPE,
    p_trc        OUT w_users.wu_trc%TYPE)
IS
BEGIN
    BEGIN
        SELECT wu_id,
               wu_wut,
               wu_org,
               wu_trc
          INTO p_uid,
               p_wut,
               p_org,
               p_trc
          FROM w_users
         WHERE wu_login = p_username;                             --v('USER');
    EXCEPTION
        WHEN OTHERS
        THEN
            BEGIN
                p_wut := 0;
                p_uid := -1;
                p_org := -1;
                p_trc := 0;
            END;
    END;
END GetUserAttr;
/


CREATE OR REPLACE PUBLIC SYNONYM GETUSERATTR FOR IKIS_SYSWEB.GETUSERATTR
/


GRANT EXECUTE ON IKIS_SYSWEB.GETUSERATTR TO II01RC_SYSWEB_COMM
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSERATTR TO IKIS_FINZVIT WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSERATTR TO IKIS_PERSON WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSERATTR TO IKIS_RBM WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSERATTR TO IKIS_WEBPROXY WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSERATTR TO USS_CEA WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSERATTR TO USS_DOC WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSERATTR TO USS_ESR WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSERATTR TO USS_EXCH WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSERATTR TO USS_NDI WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSERATTR TO USS_PERSON WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSERATTR TO USS_RNSP WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSERATTR TO USS_RPT WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.GETUSERATTR TO USS_VISIT WITH GRANT OPTION
/
