/* Formatted on 8/12/2025 6:11:35 PM (QP5 v5.417) */
CREATE OR REPLACE FUNCTION IKIS_SYSWEB.GETJOBNAME (P_JB_ID W_JOBS.JB_ID%TYPE)
    RETURN W_JOBS.JB_JOB_NAME%TYPE
IS
    L_RESULT   W_JOBS.JB_JOB_NAME%TYPE;
BEGIN
    SELECT JB_JOB_NAME
      INTO L_RESULT
      FROM W_JOBS
     WHERE JB_ID = P_JB_ID AND JB_SS_CODE IN ('IKIS_PPVP', 'IKIS_ROCD');

    RETURN L_RESULT;
END;
/
