/* Formatted on 8/12/2025 6:11:35 PM (QP5 v5.417) */
CREATE OR REPLACE FUNCTION IKIS_SYSWEB.GetNumLine (p_line NUMBER)
    RETURN T_LINES
    PIPELINED
IS
BEGIN
    FOR i IN 0 .. p_line
    LOOP
        PIPE ROW (i);
    END LOOP;

    RETURN;
END GetNumLine;
/


CREATE OR REPLACE PUBLIC SYNONYM GETNUMLINE FOR IKIS_SYSWEB.GETNUMLINE
/


GRANT EXECUTE ON IKIS_SYSWEB.GETNUMLINE TO II01RC_SYSWEB_COMM
/

GRANT EXECUTE ON IKIS_SYSWEB.GETNUMLINE TO IKIS_RBM
/

GRANT EXECUTE ON IKIS_SYSWEB.GETNUMLINE TO IKIS_WEBPROXY
/

GRANT EXECUTE ON IKIS_SYSWEB.GETNUMLINE TO USS_ESR
/

GRANT EXECUTE ON IKIS_SYSWEB.GETNUMLINE TO USS_EXCH
/

GRANT EXECUTE ON IKIS_SYSWEB.GETNUMLINE TO USS_NDI
/

GRANT EXECUTE ON IKIS_SYSWEB.GETNUMLINE TO USS_PERSON
/

GRANT EXECUTE ON IKIS_SYSWEB.GETNUMLINE TO USS_RNSP
/

GRANT EXECUTE ON IKIS_SYSWEB.GETNUMLINE TO USS_RPT
/

GRANT EXECUTE ON IKIS_SYSWEB.GETNUMLINE TO USS_VISIT
/
