/* Formatted on 8/12/2025 6:11:36 PM (QP5 v5.417) */
CREATE OR REPLACE FUNCTION IKIS_SYSWEB.is_role_assigned (
    p_username   IN VARCHAR2,
    p_role       IN VARCHAR2,
    p_user_tp       VARCHAR2)
    RETURN BOOLEAN
AS
    l_cnt   NUMBER;
BEGIN
    SELECT COUNT (1)
      INTO l_cnt
      FROM w_usr2roles
     WHERE     wr_id = (SELECT wr_id
                          FROM w_roles
                         WHERE wr_name = UPPER (p_role))
           AND wu_id =
               (SELECT wu_id
                  FROM w_users, w_user_type
                 WHERE     wu_login = UPPER (p_username)
                       AND wu_wut = wut_id
                       AND wut_code = p_user_tp);

    RETURN l_cnt > 0;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM IS_ROLE_ASSIGNED FOR IKIS_SYSWEB.IS_ROLE_ASSIGNED
/


CREATE OR REPLACE SYNONYM USS_CEA.IS_ROLE_ASSIGNED FOR IKIS_SYSWEB.IS_ROLE_ASSIGNED
/


CREATE OR REPLACE SYNONYM USS_DOC.IS_ROLE_ASSIGNED FOR IKIS_SYSWEB.IS_ROLE_ASSIGNED
/


CREATE OR REPLACE SYNONYM USS_ESR.IS_ROLE_ASSIGNED FOR IKIS_SYSWEB.IS_ROLE_ASSIGNED
/


CREATE OR REPLACE SYNONYM USS_EXCH.IS_ROLE_ASSIGNED FOR IKIS_SYSWEB.IS_ROLE_ASSIGNED
/


CREATE OR REPLACE SYNONYM USS_NDI.IS_ROLE_ASSIGNED FOR IKIS_SYSWEB.IS_ROLE_ASSIGNED
/


CREATE OR REPLACE SYNONYM USS_PERSON.IS_ROLE_ASSIGNED FOR IKIS_SYSWEB.IS_ROLE_ASSIGNED
/


CREATE OR REPLACE SYNONYM USS_RNSP.IS_ROLE_ASSIGNED FOR IKIS_SYSWEB.IS_ROLE_ASSIGNED
/


CREATE OR REPLACE SYNONYM USS_RPT.IS_ROLE_ASSIGNED FOR IKIS_SYSWEB.IS_ROLE_ASSIGNED
/


CREATE OR REPLACE SYNONYM USS_VISIT.IS_ROLE_ASSIGNED FOR IKIS_SYSWEB.IS_ROLE_ASSIGNED
/


GRANT EXECUTE ON IKIS_SYSWEB.IS_ROLE_ASSIGNED TO IKIS_FINZVIT WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IS_ROLE_ASSIGNED TO IKIS_PERSON WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IS_ROLE_ASSIGNED TO IKIS_RBM WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IS_ROLE_ASSIGNED TO IKIS_WEBPROXY WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IS_ROLE_ASSIGNED TO USS_CEA WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IS_ROLE_ASSIGNED TO USS_DOC WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IS_ROLE_ASSIGNED TO USS_ESR WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IS_ROLE_ASSIGNED TO USS_EXCH WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IS_ROLE_ASSIGNED TO USS_NDI WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IS_ROLE_ASSIGNED TO USS_PERSON WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IS_ROLE_ASSIGNED TO USS_RNSP WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IS_ROLE_ASSIGNED TO USS_RPT WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYSWEB.IS_ROLE_ASSIGNED TO USS_VISIT WITH GRANT OPTION
/
