/* Formatted on 8/12/2025 6:10:11 PM (QP5 v5.417) */
CREATE OR REPLACE FUNCTION IKIS_SYS.GetCurrentUserId
    RETURN NUMBER
    AUTHID CURRENT_USER
IS
    Result                NUMBER;
    -- Messages for category: COMMON
    msgCOMMON_EXCEPTION   NUMBER := 2;
    msgNODATAFOUND        NUMBER := 954;
BEGIN
    SELECT v_ikis_users_curr.iu_oraid INTO Result FROM v_ikis_users_curr;

    RETURN (Result);
EXCEPTION
    WHEN NO_DATA_FOUND
    THEN
        raise_application_error (
            -20000,
            ikis_message_util.GET_MESSAGE (
                msgNODATAFOUND,
                'отримання ІД поточного користувача ІКІС'));
    WHEN OTHERS
    THEN
        raise_application_error (
            -20000,
            ikis_message_util.GET_MESSAGE (msgCOMMON_EXCEPTION,
                                           'GetCurrentUserId',
                                           CHR (10) || SQLERRM));
END GetCurrentUserId;
/


CREATE OR REPLACE PUBLIC SYNONYM GETCURRENTUSERID FOR IKIS_SYS.GETCURRENTUSERID
/


GRANT EXECUTE ON IKIS_SYS.GETCURRENTUSERID TO II01RC_IKIS_COMMON
/

GRANT EXECUTE ON IKIS_SYS.GETCURRENTUSERID TO IKIS_FINZVIT WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.GETCURRENTUSERID TO IKIS_PERSON WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.GETCURRENTUSERID TO IKIS_RBM WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.GETCURRENTUSERID TO IKIS_SYSWEB WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.GETCURRENTUSERID TO USS_CEA WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.GETCURRENTUSERID TO USS_DOC WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.GETCURRENTUSERID TO USS_ESR WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.GETCURRENTUSERID TO USS_EXCH WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.GETCURRENTUSERID TO USS_NDI WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.GETCURRENTUSERID TO USS_PERSON WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.GETCURRENTUSERID TO USS_RNSP WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.GETCURRENTUSERID TO USS_RPT WITH GRANT OPTION
/

GRANT EXECUTE ON IKIS_SYS.GETCURRENTUSERID TO USS_VISIT WITH GRANT OPTION
/
