/* Formatted on 8/12/2025 6:10:11 PM (QP5 v5.417) */
CREATE OR REPLACE FUNCTION IKIS_SYS.DS_DEFAULT
    RETURN NUMBER
IS
    l_newid   DECIMAL;
BEGIN
    SELECT SQ_OTH_DEFAULT.NEXTVAL INTO l_newid FROM DUAL;

    DSERIALS.gd_serial_Last := DSERIALS.gd_serial_diapason + l_newid;
    RETURN DSERIALS.gd_serial_Last;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM DS_DEFAULT FOR IKIS_SYS.DS_DEFAULT
/


GRANT EXECUTE ON IKIS_SYS.DS_DEFAULT TO II01RC_IKIS_COMMON
/

GRANT EXECUTE ON IKIS_SYS.DS_DEFAULT TO II01RC_IKIS_DESIGN
/
