/* Formatted on 8/12/2025 6:00:10 PM (QP5 v5.417) */
CREATE OR REPLACE FUNCTION USS_VISIT.Bool2str (p_Bool BOOLEAN)
    RETURN VARCHAR2
IS
BEGIN
    RETURN CASE WHEN p_Bool THEN 'T' ELSE 'F' END;
END Bool2str;
/
