/* Formatted on 8/12/2025 6:00:10 PM (QP5 v5.417) */
CREATE OR REPLACE FUNCTION USS_VISIT.Str2bool (p_Str VARCHAR2)
    RETURN BOOLEAN
IS
BEGIN
    RETURN CASE WHEN p_Str = 'T' THEN TRUE ELSE FALSE END;
END;
/
