/* Formatted on 8/12/2025 6:10:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IBR_ID_SR_WORK
    BEFORE INSERT
    ON IKIS_SYS.SR_WORK
    FOR EACH ROW
    DISABLE
BEGIN
    :NEW.w_id := ID_SR_WORK (:NEW.w_id);
END;
/
