/* Formatted on 8/12/2025 6:10:09 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IBR_DID_IKIS_PROTOCOL
    BEFORE INSERT
    ON IKIS_SYS.IKIS_PROTOCOL
    FOR EACH ROW
BEGIN
    IF dserials.gd_idiap_enabled
    THEN
        :NEW.PROT_ID := DID_IKIS_PROTOCOL (:NEW.PROT_ID);
    END IF;
END;
/
