/* Formatted on 8/12/2025 6:06:34 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_RPT_FRAME
    BEFORE INSERT
    ON IKIS_FINZVIT.RPT_FRAME
    FOR EACH ROW
BEGIN
    :NEW.RF_ID := DID_RPT_FRAME (:NEW.RF_ID);
END;
/
