/* Formatted on 8/12/2025 6:06:33 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_BUDGET_PFU
    BEFORE INSERT
    ON IKIS_FINZVIT.BUDGET_PFU
    FOR EACH ROW
BEGIN
    :NEW.BP_ID := DID_BUDGET_PFU (:NEW.BP_ID);
END;
/
