/* Formatted on 8/12/2025 6:10:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IBR_ID_SR_PROTOCOL
    BEFORE INSERT
    ON IKIS_SYS.SR_PROTOCOL
    FOR EACH ROW
BEGIN
    :NEW.prot_id := ID_SR_PROTOCOL (:NEW.prot_id);
END;
/
