/* Formatted on 8/12/2025 6:11:32 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYSWEB.IBR_ID_W_FILE$SUBSYS
    BEFORE INSERT
    ON IKIS_SYSWEB.W_FILE$SUBSYS
    FOR EACH ROW
BEGIN
    :NEW.WFS_ID := ID_W_FILE$SUBSYS (:NEW.WFS_ID);
END;
/
