/* Formatted on 8/12/2025 6:07:20 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_PERSON.IBR_ID_DOCUMENT_DATA
    BEFORE INSERT
    ON IKIS_PERSON.DOCUMENT_DATA
    FOR EACH ROW
BEGIN
    IF (:NEW.dc_id = 0) OR (:NEW.dc_id IS NULL)
    THEN
        :NEW.dc_id := ID_DOCUMENT_DATA (p_id => :NEW.dc_id);
    END IF;
END;
/
