/* Formatted on 8/12/2025 6:11:32 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYSWEB.TID$BLD$UPGRADE
    BEFORE INSERT
    ON IKIS_SYSWEB.BLD$UPGRADE
    FOR EACH ROW
DECLARE
    l_id   NUMBER;
BEGIN
    SELECT SQ$BLD$UPGRADE.NEXTVAL INTO l_id FROM DUAL;

    :NEW.bldu_id := l_id;
    :NEW.bldu_order := l_id;
END;
/
