/* Formatted on 8/12/2025 6:06:34 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_PAY_ORDER
    BEFORE INSERT
    ON IKIS_FINZVIT.PAY_ORDER
    FOR EACH ROW
BEGIN
    :NEW.PO_ID := DID_PAY_ORDER (:NEW.PO_ID);
END;
/
