/* Formatted on 8/12/2025 6:06:34 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_DISTRIB_LINE
    BEFORE INSERT
    ON IKIS_FINZVIT.DISTRIB_LINE
    FOR EACH ROW
BEGIN
    :NEW.DL_ID := DID_DISTRIB_LINE (:NEW.DL_ID);
END;
/
