/* Formatted on 8/12/2025 6:06:34 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_RPT_INLINE_DATA
    BEFORE INSERT
    ON IKIS_FINZVIT.RPT_INLINE_DATA
    FOR EACH ROW
BEGIN
    :NEW.IRD_ID := DID_RPT_INLINE_DATA (:NEW.IRD_ID);
END;
/
