/* Formatted on 8/12/2025 6:10:09 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IBR_CHANGE_UPD
    BEFORE UPDATE OR DELETE
    ON IKIS_SYS.IKIS_CHANGES
    FOR EACH ROW
DECLARE
BEGIN
    IKIS_CHANGES_UTL.UpdateDeleteError;
END IBR_CHANGE_UPD;
/
