/* Formatted on 8/12/2025 6:06:34 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_RPT_PACK_JOURNAL
    BEFORE INSERT
    ON IKIS_FINZVIT.RPT_PACK_JOURNAL
    FOR EACH ROW
BEGIN
    :NEW.RPJ_ID := DID_RPT_PACK_JOURNAL (:NEW.RPJ_ID);
END;
/
