/* Formatted on 8/12/2025 6:06:34 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_RPT_PACK
    BEFORE INSERT
    ON IKIS_FINZVIT.RPT_PACK
    FOR EACH ROW
BEGIN
    :NEW.RP_ID := DID_RPT_PACK (:NEW.RP_ID);
END;
/
