/* Formatted on 8/12/2025 6:10:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IBR_ID_SR_CONTROLS
    BEFORE INSERT
    ON IKIS_SYS.SR_CONTROLS
    FOR EACH ROW
    DISABLE
BEGIN
    :NEW.cntr_id := ID_SR_CONTROLS (:NEW.cntr_id);
END;
/
