/* Formatted on 8/12/2025 6:11:32 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYSWEB.IBR_ID_W_FILE$INFO
    BEFORE INSERT
    ON IKIS_SYSWEB.W_FILE$INFO
    FOR EACH ROW
BEGIN
    :NEW.WF_ID := ID_W_FILE$INFO (:NEW.WF_ID);
END;
/
