/* Formatted on 8/12/2025 6:06:33 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_BUDGET_ORG2ITEM
    BEFORE INSERT
    ON IKIS_FINZVIT.BUDGET_ORG2ITEM
    FOR EACH ROW
BEGIN
    :NEW.BO2I_ID := DID_BUDGET_ORG2ITEM (:NEW.BO2I_ID);
END;
/
