/* Formatted on 8/12/2025 6:06:33 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_DIC_DKG_PO_TEMPLATE
    BEFORE INSERT
    ON IKIS_FINZVIT.DIC_DKG_PO_TEMPLATE
    FOR EACH ROW
BEGIN
    :NEW.DPT_ID := DID_DIC_DKG_PO_TEMPLATE (:NEW.DPT_ID);
END;
/
