/* Formatted on 8/12/2025 6:10:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.I_APPT_AUDIT
    BEFORE INSERT
    ON IKIS_SYS.APPT_AUDIT
    FOR EACH ROW
BEGIN
    :NEW.aud_ID := ds_audit (:NEW.aud_ID);
END;
/
