/* Formatted on 8/12/2025 6:12:50 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_WEBPROXY."INSERT_DEMO_PROD"
    BEFORE INSERT
    ON IKIS_WEBPROXY.DEMO_PRODUCT_INFO
    FOR EACH ROW
DECLARE
    prod_id   NUMBER;
BEGIN
    SELECT demo_prod_seq.NEXTVAL INTO prod_id FROM DUAL;

    :new.PRODUCT_ID := prod_id;
END;
/
