/* Formatted on 8/12/2025 6:11:32 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYSWEB.IBR_ID_W_LOGIN_ATTEMPTS
    BEFORE INSERT
    ON ikis_sysweb.W_LOGIN_ATTEMPTS
    FOR EACH ROW
BEGIN
    :NEW.wla_id := ID_W_LOGIN_ATTEMPTS (:NEW.wla_id);
END;
/
