/* Formatted on 8/12/2025 6:10:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IBR_ID_SR_TEMPLATE
    BEFORE INSERT
    ON IKIS_SYS.SR_TEMPLATE
    FOR EACH ROW
BEGIN
    :NEW.tm_id := ID_SR_TEMPLATE (:NEW.tm_id);
END;
/
