/* Formatted on 8/12/2025 6:10:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IBR_ID_IKIS_CHANGES_TEMPL
    BEFORE INSERT
    ON IKIS_SYS.IKIS_CHANGES_TEMPL
    FOR EACH ROW
BEGIN
    :NEW.ict_id := ID_IKIS_CHANGES_TEMPL (:NEW.ict_id);
END;
/
