/* Formatted on 8/12/2025 6:06:34 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_DKG_PO_REQUEST
    BEFORE INSERT
    ON IKIS_FINZVIT.DKG_PO_REQUEST
    FOR EACH ROW
BEGIN
    :NEW.DPR_ID := DID_DKG_PO_REQUEST (:NEW.DPR_ID);
END;
/
