/* Formatted on 8/12/2025 6:10:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IBR_ID_IKIS_AUD_OPER
    BEFORE INSERT
    ON IKIS_SYS.IKIS_AUD_OPER
    FOR EACH ROW
BEGIN
    :NEW.AO_ID := ID_IKIS_AUD_OPER (:NEW.AO_ID);
END;
/
