/* Formatted on 8/12/2025 6:12:50 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_WEBPROXY."bi_ITSMHOST"
    BEFORE INSERT
    ON IKIS_WEBPROXY.TMP_ITSMHOST
    FOR EACH ROW
BEGIN
    IF :new."ID" IS NULL
    THEN
        SELECT "ITSMHOST_SEQ".NEXTVAL INTO :new."ID" FROM DUAL;
    END IF;
END;
/
