/* Formatted on 8/12/2025 6:10:55 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_RBM.IBR_ID_PACKET_CONTENT
    BEFORE INSERT
    ON IKIS_RBM.PACKET_CONTENT
    FOR EACH ROW
BEGIN
    IF (:NEW.pc_id = 0) OR (:NEW.pc_id IS NULL)
    THEN
        :NEW.pc_id := ID_PACKET_CONTENT (:NEW.pc_id);
    END IF;
END;
/
