/* Formatted on 8/12/2025 6:10:55 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_RBM.IBR_ID_PORTAL_USER_SESSION
    BEFORE INSERT
    ON ikis_rbm.PORTAL_USER_SESSION
    FOR EACH ROW
BEGIN
    IF (:NEW.PUS_ID = 0) OR (:NEW.PUS_ID IS NULL)
    THEN
        :NEW.PUS_ID := ID_PORTAL_USER_SESSION (:NEW.PUS_ID);
    END IF;
END;
/
