/* Formatted on 8/12/2025 6:11:32 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYSWEB.IBR_ID_SCHEDULER_JOB_PARAMS
    BEFORE INSERT
    ON IKIS_SYSWEB.SCHEDULER_JOB_PARAMS
    FOR EACH ROW
BEGIN
    :NEW.sjp_id := id_scheduler_job_params (:NEW.sjp_id);
END IBR_ID_SCHEDULER_JOB_PARAMS;
/
