/* Formatted on 8/12/2025 6:10:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.TID$BLD$VERSION
    BEFORE INSERT
    ON IKIS_SYS.BLD$VERSION
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT SQ$BLD$VERSION.NEXTVAL INTO :NEW.bldv_id FROM DUAL;
END;
/
