/* Formatted on 8/12/2025 6:06:34 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_RPT_ROW_TP
    BEFORE INSERT
    ON IKIS_FINZVIT.RPT_ROW_TP
    FOR EACH ROW
BEGIN
    :NEW.RRT_ID := DID_RPT_ROW_TP (:NEW.RRT_ID);
END;
/
