/* Formatted on 8/12/2025 6:06:34 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_PPVP_PO_LINK
    BEFORE INSERT
    ON IKIS_FINZVIT.PPVP_PO_LINK
    FOR EACH ROW
BEGIN
    :NEW.PPL_ID := DID_PPVP_PO_LINK (:NEW.PPL_ID);
END;
/
