/* Formatted on 8/12/2025 6:10:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IUBR_REPL_ikis_users_attr_TS
    BEFORE INSERT OR UPDATE
    ON IKIS_SYS.IKIS_USERS_ATTR
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    IF DSERIALS.gd_ts_enabled
    THEN
        DSERIALS.GetNextTimestamp (:NEW.REPL_TS);
    END IF;
END;
/
