/* Formatted on 8/12/2025 6:06:34 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_DIC_PPVP_PO_TEMPLATE
    BEFORE INSERT
    ON IKIS_FINZVIT.DIC_PPVP_PO_TEMPLATE
    FOR EACH ROW
BEGIN
    :NEW.PPT_ID := DID_DIC_PPVP_PO_TEMPLATE (:NEW.PPT_ID);
END;
/
