/* Formatted on 8/12/2025 6:12:50 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_WEBPROXY."INSERT_DEMO_CUST"
    BEFORE INSERT
    ON IKIS_WEBPROXY.DEMO_CUSTOMERS
    FOR EACH ROW
DECLARE
    cust_id   NUMBER;
BEGIN
    SELECT demo_cust_seq.NEXTVAL INTO cust_id FROM DUAL;

    :new.CUSTOMER_ID := cust_id;
END;
/
