/* Formatted on 8/12/2025 6:06:33 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_BUDGET_ORG_JOURNAL
    BEFORE INSERT
    ON IKIS_FINZVIT.BUDGET_ORG_JOURNAL
    FOR EACH ROW
BEGIN
    :NEW.BOJ_ID := DID_BUDGET_ORG_JOURNAL (:NEW.BOJ_ID);
END;
/
