/* Formatted on 8/12/2025 6:11:32 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYSWEB.IBR_DID_DNET_SESSION
    BEFORE INSERT
    ON ikis_sysweb.DNET_SESSION
    FOR EACH ROW
BEGIN
    :NEW.DS_ID := DID_DNET_SESSION (:NEW.DS_ID);
END;
/
