/* Formatted on 8/12/2025 6:10:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IBR_ID_SR_GROUP_FINAL
    BEFORE INSERT
    ON IKIS_SYS.SR_GROUP_FINAL
    FOR EACH ROW
    DISABLE
BEGIN
    :NEW.gf_id := ID_SR_GROUP_FINAL (:NEW.gf_id);
END;
/
