/* Formatted on 8/12/2025 6:06:34 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_RPT_TEMPLATE
    BEFORE INSERT
    ON IKIS_FINZVIT.RPT_TEMPLATE
    FOR EACH ROW
BEGIN
    :NEW.RT_ID := DID_RPT_TEMPLATE (:NEW.RT_ID);
END;
/
