/* Formatted on 8/12/2025 6:12:49 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_WEBPROXY."DEMO_USERS_T1"
    BEFORE INSERT OR UPDATE
    ON IKIS_WEBPROXY.DEMO_USERS
    FOR EACH ROW
BEGIN
    :NEW.user_name := UPPER (:NEW.user_name);
END;
/
