/* Formatted on 8/12/2025 6:06:33 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_BUDGET_PFU_JOURNAL
    BEFORE INSERT
    ON IKIS_FINZVIT.BUDGET_PFU_JOURNAL
    FOR EACH ROW
BEGIN
    :NEW.BPJ_ID := DID_BUDGET_PFU_JOURNAL (:NEW.BPJ_ID);
END;
/
