/* Formatted on 8/12/2025 6:06:33 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_BUDGET_ORG
    BEFORE INSERT
    ON IKIS_FINZVIT.BUDGET_ORG
    FOR EACH ROW
BEGIN
    :NEW.BO_ID := DID_BUDGET_ORG (:NEW.BO_ID);
END;
/
