/* Formatted on 8/12/2025 6:06:34 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_DISTRIB_ARTICLE
    BEFORE INSERT
    ON IKIS_FINZVIT.DISTRIB_ARTICLE
    FOR EACH ROW
BEGIN
    :NEW.DA_ID := DID_DISTRIB_ARTICLE (:NEW.DA_ID);
END;
/
