/* Formatted on 8/12/2025 6:12:49 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_WEBPROXY.IBR_ID_ITAZ_SETUP_PARAM
    BEFORE INSERT
    ON IKIS_WEBPROXY.ITAZ_SETUP_PARAM
    FOR EACH ROW
BEGIN
    IF (:NEW.sprm_id = 0) OR (:NEW.sprm_id IS NULL)
    THEN
        :NEW.sprm_id := ID_ITAZ_SETUP_PARAM (:NEW.sprm_id);
    END IF;
END;
/
