/* Formatted on 8/12/2025 6:10:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IBR_ID_FILE_JOB
    BEFORE INSERT
    ON IKIS_SYS.FILE_JOB
    FOR EACH ROW
BEGIN
    :NEW.fj_id := ID_FILE_JOB (:NEW.fj_id);
END;
/
