/* Formatted on 8/12/2025 6:06:33 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_DIC_PAY_PERSON
    BEFORE INSERT
    ON IKIS_FINZVIT.DIC_PAY_PERSON
    FOR EACH ROW
BEGIN
    :NEW.DPP_ID := DID_DIC_PAY_PERSON (:NEW.DPP_ID);
END;
/
