/* Formatted on 8/12/2025 6:10:55 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_RBM.IBR_ID_MESSAGETEMPLATES
    BEFORE INSERT
    ON IKIS_RBM.MESSAGETEMPLATES
    FOR EACH ROW
BEGIN
    IF (:NEW.mt_id = 0) OR (:NEW.mt_id IS NULL)
    THEN
        :NEW.mt_id := ID_MESSAGETEMPLATES (:NEW.mt_id);
    END IF;
END;
/
