/* Formatted on 8/12/2025 6:06:34 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IUBR_RPT_PACK_CT
    BEFORE INSERT OR UPDATE
    ON IKIS_FINZVIT.RPT_PACK
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    SET_CHANGE_TS (:NEW.CHANGE_TS);
END;
/
