/* Formatted on 8/12/2025 6:11:32 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYSWEB.TID$BLD$PROJDETAIL
    BEFORE INSERT
    ON IKIS_SYSWEB.BLD$PROJDETAIL
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
DECLARE
    l_id   NUMBER;
BEGIN
    SELECT SQ$BLD$PROJDETAIL.NEXTVAL INTO l_id FROM DUAL;

    :NEW.bldd_id := l_id;
    :NEW.bldd_order := l_id;
END;
/
