/* Formatted on 8/12/2025 6:10:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IBR_ID_FILE_JOB_EXCEPTION
    BEFORE INSERT
    ON IKIS_SYS.FILE_JOB_EXCEPTION
    FOR EACH ROW
BEGIN
    :NEW.fje_id := ID_FILE_JOB_EXCEPTION (:NEW.fje_id);
END;
/
