/* Formatted on 8/12/2025 6:10:55 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_RBM.IBR_ID_PACKET_PROCESSING
    BEFORE INSERT
    ON IKIS_RBM.PACKET_PROCESSING
    FOR EACH ROW
BEGIN
    IF (:NEW.pp_id = 0) OR (:NEW.pp_id IS NULL)
    THEN
        :NEW.pp_id := ID_PACKET_PROCESSING (:NEW.pp_id);
    END IF;
END;
/
