/* Formatted on 8/12/2025 6:07:20 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_PERSON.IBR_ID_INSURED_PERSON
    BEFORE INSERT
    ON IKIS_PERSON.INSURED_PERSON
    FOR EACH ROW
BEGIN
    IF (:NEW.ip_id = 0) OR (:NEW.ip_id IS NULL)
    THEN
        :NEW.ip_id := ID_INSURED_PERSON (p_id => :NEW.ip_id);
    END IF;
END;
/
