/* Formatted on 8/12/2025 6:06:33 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_DIC_ARTICLE_IN_PURPOSE
    BEFORE INSERT
    ON IKIS_FINZVIT.DIC_ARTICLE_IN_PURPOSE
    FOR EACH ROW
BEGIN
    :NEW.DAP_ID := DID_DIC_ARTICLE_IN_PURPOSE (:NEW.DAP_ID);
END;
/
