/* Formatted on 8/12/2025 6:10:09 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IBR_DID_IKIS_EXCEPTION_LOG
    BEFORE INSERT
    ON IKIS_SYS.IKIS_EXCEPTION_LOG
    FOR EACH ROW
BEGIN
    IF dserials.gd_idiap_enabled
    THEN
        :NEW.iel_id := DID_IKIS_EXCEPTION_LOG (:NEW.iel_id);
    END IF;
END;
/
