/* Formatted on 8/12/2025 6:10:55 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_RBM.IBR_ID_AUTO_USER
    BEFORE INSERT
    ON ikis_rbm.AUTO_USER
    FOR EACH ROW
BEGIN
    IF (:NEW.AU_ID = 0) OR (:NEW.AU_ID IS NULL)
    THEN
        :NEW.AU_ID := ID_AUTO_USER (:NEW.AU_ID);
    END IF;
END;
/
