/* Formatted on 8/12/2025 6:10:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IBR_ID_FILE_TYPE_PARAMETER
    BEFORE INSERT
    ON IKIS_SYS.FILE_TYPE_PARAMETER
    FOR EACH ROW
BEGIN
    :NEW.ftp_id := ID_FILE_TYPE_PARAMETER (:NEW.ftp_id);
END;
/
