/* Formatted on 8/12/2025 6:10:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IBR_ID_IKIS_FLDTBL4LOAD
    BEFORE INSERT
    ON IKIS_SYS.IKIS_FLDTBL4LOAD
    FOR EACH ROW
BEGIN
    :NEW.fdt_id := ID_IKIS_FLDTBL4LOAD (:NEW.fdt_id);
END;
/
