/* Formatted on 8/12/2025 6:06:33 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_BUDGET_PFU2ITEM2ORG
    BEFORE INSERT
    ON IKIS_FINZVIT.BUDGET_PFU2ITEM2ORG
    FOR EACH ROW
BEGIN
    :NEW.BP2I2O_ID := DID_BUDGET_PFU2ITEM2ORG (:NEW.BP2I2O_ID);
END;
/
