/* Formatted on 8/12/2025 6:10:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IBR_ID_SR_GROUP_LINKS
    BEFORE INSERT
    ON IKIS_SYS.SR_GROUP_LINKS
    FOR EACH ROW
    DISABLE
BEGIN
    :NEW.grpl_id := ID_SR_GROUP_LINKS (:NEW.grpl_id);
END;
/
