/* Formatted on 8/12/2025 6:06:34 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_REPORT
    BEFORE INSERT
    ON IKIS_FINZVIT.REPORT
    FOR EACH ROW
BEGIN
    :NEW.RPT_ID := DID_REPORT (:NEW.RPT_ID);
END;
/
