/* Formatted on 8/12/2025 6:06:33 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_AGGR_PACK
    BEFORE INSERT
    ON IKIS_FINZVIT.AGGR_PACK
    FOR EACH ROW
BEGIN
    :NEW.AP_ID := DID_AGGR_PACK (:NEW.AP_ID);
END;
/
