/* Formatted on 8/12/2025 6:06:34 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_DISTRIB_PO_SETUP_LINE
    BEFORE INSERT
    ON IKIS_FINZVIT.DISTRIB_PO_SETUP_LINE
    FOR EACH ROW
BEGIN
    :NEW.DSL_ID := DID_DISTRIB_PO_SETUP_LINE (:NEW.DSL_ID);
END;
/
