/* Formatted on 8/12/2025 6:10:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IBR_ID_FILE_TYPE
    BEFORE INSERT
    ON IKIS_SYS.FILE_TYPE
    FOR EACH ROW
BEGIN
    :NEW.ft_id := ID_FILE_TYPE (:NEW.ft_id);
END;
/
