/* Formatted on 8/12/2025 6:11:32 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYSWEB.TID$BLD$PROJECTS
    BEFORE INSERT
    ON IKIS_SYSWEB.BLD$PROJECTS
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
DECLARE
    l_id   NUMBER;
BEGIN
    SELECT SQ$BLD$PROJECTS.NEXTVAL INTO l_id FROM DUAL;

    :NEW.bldp_id := l_id;
    :NEW.bldp_order := l_id;
END;
/
