/* Formatted on 8/12/2025 6:06:34 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_RPT_FRAME_TEMPLATE
    BEFORE INSERT
    ON IKIS_FINZVIT.RPT_FRAME_TEMPLATE
    FOR EACH ROW
BEGIN
    :NEW.RFT_ID := DID_RPT_FRAME_TEMPLATE (:NEW.RFT_ID);
END;
/
