/* Formatted on 8/12/2025 6:06:34 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_DISTRIB_MAIN
    BEFORE INSERT
    ON IKIS_FINZVIT.DISTRIB_MAIN
    FOR EACH ROW
BEGIN
    :NEW.DM_ID := DID_DISTRIB_MAIN (:NEW.DM_ID);
END;
/
