/* Formatted on 8/12/2025 6:10:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IBR_ID_IKIS_PROT_TYPE
    BEFORE INSERT
    ON IKIS_SYS.IKIS_PROT_TYPE
    FOR EACH ROW
BEGIN
    :NEW.TYPE_ID := ID_IKIS_PROT_TYPE (:NEW.TYPE_ID);
END;
/
