/* Formatted on 8/12/2025 6:10:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_SYS.IBR_ID_IKIS_TBL4LOAD
    BEFORE INSERT
    ON IKIS_SYS.IKIS_TBL4LOAD
    FOR EACH ROW
BEGIN
    :NEW.tbl_id := ID_IKIS_TBL4LOAD (:NEW.tbl_id);
END;
/
