/* Formatted on 8/12/2025 6:06:33 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER IKIS_FINZVIT.IBR_DID_DIC_DISTRIB_PURPOSE_GR
    BEFORE INSERT
    ON IKIS_FINZVIT.DIC_DISTRIB_PURPOSE_GR
    FOR EACH ROW
BEGIN
    :NEW.DPG_ID := DID_DIC_DISTRIB_PURPOSE_GR (:NEW.DPG_ID);
END;
/
