/* Formatted on 8/12/2025 5:58:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER USS_RNSP.IBR_ID_RNSP_OTHER
    BEFORE INSERT
    ON uss_rnsp.RNSP_OTHER
    FOR EACH ROW
BEGIN
    IF (:NEW.RNSPO_ID = 0) OR (:NEW.RNSPO_ID IS NULL)
    THEN
        :NEW.RNSPO_ID := ID_RNSP_OTHER (:NEW.RNSPO_ID);
    END IF;
END;
/
