/* Formatted on 8/12/2025 5:58:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER USS_RNSP.IBR_ID_RNSP_ADDRESS
    BEFORE INSERT
    ON uss_rnsp.RNSP_ADDRESS
    FOR EACH ROW
BEGIN
    IF (:NEW.RNSPA_ID = 0) OR (:NEW.RNSPA_ID IS NULL)
    THEN
        :NEW.RNSPA_ID := ID_RNSP_ADDRESS (:NEW.RNSPA_ID);
    END IF;
END;
/
