/* Formatted on 8/12/2025 6:00:12 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER USS_VISIT.UBR_OPT_APPEAL
    BEFORE INSERT OR UPDATE
    ON uss_visit.appeal
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    IF API$INTERNAL.is_obi_enabled
    THEN
        SELECT SQ_OPT_appeal.NEXTVAL INTO :NEW.obi_ts FROM DUAL;
    END IF;
END;
/
