/* Formatted on 8/12/2025 5:58:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER USS_RNSP.IBR_ID_RNSP_CHECK
    BEFORE INSERT
    ON uss_rnsp.RNSP_CHECK
    FOR EACH ROW
BEGIN
    IF (:NEW.RNSPC_ID = 0) OR (:NEW.RNSPC_ID IS NULL)
    THEN
        :NEW.RNSPC_ID := ID_RNSP_CHECK (:NEW.RNSPC_ID);
    END IF;
END;
/
