/* Formatted on 8/12/2025 5:58:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER USS_RNSP.IBR_ID_RNSP_STATUS_REGISTER
    BEFORE INSERT
    ON uss_rnsp.RNSP_STATUS_REGISTER
    FOR EACH ROW
BEGIN
    IF (:NEW.RNSPSR_ID = 0) OR (:NEW.RNSPSR_ID IS NULL)
    THEN
        :NEW.RNSPSR_ID := ID_RNSP_STATUS_REGISTER (:NEW.RNSPSR_ID);
    END IF;
END;
/
