/* Formatted on 8/12/2025 5:58:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER USS_RNSP.IBR_ID_RNSP_STATE
    BEFORE INSERT
    ON uss_rnsp.RNSP_STATE
    FOR EACH ROW
BEGIN
    IF (:NEW.RNSPS_ID = 0) OR (:NEW.RNSPS_ID IS NULL)
    THEN
        :NEW.RNSPS_ID := ID_RNSP_STATE (:NEW.RNSPS_ID);
    END IF;
END;
/
