/* Formatted on 8/12/2025 5:58:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER USS_RNSP.IBR_ID_RNSP2ADDRESS
    BEFORE INSERT
    ON uss_rnsp.RNSP2ADDRESS
    FOR EACH ROW
BEGIN
    IF (:NEW.RNSP2A_ID = 0) OR (:NEW.RNSP2A_ID IS NULL)
    THEN
        :NEW.RNSP2A_ID := ID_RNSP2ADDRESS (:NEW.RNSP2A_ID);
    END IF;
END;
/
