/* Formatted on 8/12/2025 5:58:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER USS_RNSP.IBR_ID_RNSP_MAIN
    BEFORE INSERT
    ON uss_rnsp.RNSP_MAIN
    FOR EACH ROW
BEGIN
    IF (:NEW.RNSPM_ID = 0) OR (:NEW.RNSPM_ID IS NULL)
    THEN
        :NEW.RNSPM_ID := ID_RNSP_MAIN (:NEW.RNSPM_ID);
    END IF;
END;
/
