/* Formatted on 8/12/2025 5:58:10 PM (QP5 v5.417) */
CREATE OR REPLACE TRIGGER USS_RNSP.IBR_ID_RNSP_DICT_SERVICE
    BEFORE INSERT
    ON uss_rnsp.RNSP_DICT_SERVICE
    FOR EACH ROW
BEGIN
    IF (:NEW.RNSPDS_ID = 0) OR (:NEW.RNSPDS_ID IS NULL)
    THEN
        :NEW.RNSPDS_ID := ID_RNSP_DICT_SERVICE (:NEW.RNSPDS_ID);
    END IF;
END;
/
